name: 'jira-link-in-pr-description-action'
description: "ensures PRs can link to JIRA card"
branding:
  icon: 'check'
  color: 'green'
author: 'samueldevine'
inputs:
  project:
    required: true
    description: 'JIRA Project'
  ignore-author:
    required: false
    description: "comma seperated list of authors to skip check for"
runs:
  using: 'node20'
  main: 'dist/index.js'
